services:
  postgres:
    platform: linux/amd64
    image: postgres:16-alpine
    container_name: hrdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c listen_addresses='*'
      -c password_encryption=scram-sha-256
volumes:
  pgdata: {}