[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npm run build',
  'npx prisma generate',
  'npx prisma migrate deploy'
]

[start]
cmd = 'npm run start:prod'

